### ISSUE TITLE
'comfy' is not defined

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [GavChap/ComfyUI-SD3LatentSelectRes#1]
!!! Exception during processing!!! name 'comfy' is not defined
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 148, in recursive_execute
    obj = class_def()
          ^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SD3LatentSelectRes\sd3latentselectres.py", line 7, in __init__
    self.device = comfy.model_management.intermediate_device()
                  ^^^^^
NameError: name 'comfy' is not defined

**Comment by GalaxyTimeMachine** [comment]
I manually added the missing `import comfy` into the node, but then get this error:
```
!!! Exception during processing!!! SD3LatentSelectRes.return_res() got an unexpected keyword argument 'batch_size'
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SD3LatentSelectRes.return_res() got an unexpected keyword argument 'batch_size'
```
I think it needs some testing.

**Comment by GalaxyTimeMachine** [comment]
Created a PR for these issues.

**Comment by GavChap** [comment]
Done and fixed
